### ISSUE TITLE
Issue Internal

### ISSUE THREAD

**Issue by Canis1219** [citec-spbu/agro-artefacts#81]
Issue создан для обсуждений

**Comment by LubovMi** [comment]
**Общее собрание - 23.10.2024**

Обсудили выполненные задачи за неделю. 

-Подача на стартап будет в начале ноября (Андрей)
-Преимущество нашего проекта: бесплатное приложение с готовым интерфейсом. Первая версия – для научной деятельности(Джурабек)
-Преимущество: будем внедрять датчики
-Необходимо начать работу над дизайном, его делаем простым (для начала), согласовываем и координируем работу с Евгением Павловичем и Владом

Далее разошлись по отдельным комнатам для фронта и бэка для обсуждения новых задач

**Comment by Canis1219** [comment]
[Тестирование формы регистрации и авторизации.docx](https://github.com/user-attachments/files/18193051/default.docx)

**Comment by Canis1219** [comment]
https://www.figma.com/design/BaxQiA3A5CxJFbbpQDIxlt/Untitled?node-id=0-1  
Макет

**Comment by Canis1219** [comment]
[4_Калинкина С. (2).pdf](https://github.com/user-attachments/files/18193142/4_.2.pdf)
презентация Демо-день
