### ISSUE TITLE
Mv repos in citec-spbu

### ISSUE THREAD

**Issue by asavershin** [citec-spbu/agro-artefacts#91]
Надо осуществить переезд части репозиториев:

- [x]  field-and-crops
- [x]  agromelio-frontend
- [x]  auth-service
- [x]  profiles-service
- [x]  artefacts
- [x]  frontend-to-backend
- [x]  meteo-service
- [x]  kafka
- [x]  api-gateway

В новой организации надо создать команду с названием agro(Если названия можно давать), добавить всех участник в эту команду. Сделать так, чтобы участники команды видели только свои репоитории, либо хотя бы имели возможность увидеть свои с помощью фильтрации

Уточнить вопрос переезда фронтент репозиториев с @VorobyovVV

**Comment by Canis1219** [comment]
Уточнила у Влада- надо перенести agromelio-frontend

**Comment by Canis1219** [comment]
Перенесла перечисленные репозитории с приставкой перед названием "agro-"
Репозиторий kafka без приставки
